### ISSUE TITLE
podArgs Documentation

### ISSUE THREAD

**Issue by jgillich** [hyperhq/hyperd#458]
From the API docs:

> POST /pod/create?podArgs=****
> The argument is a string, which converts the Pod's json to a string.

I have no idea what that means. In what format should podArgs be? And what is the content of podArgs?

**Comment by jgillich** [comment]
Ok, seems like you're supposed to send the [Podfile](https://docs.hypercontainer.io/reference/podfile.html) in the body.

**Comment by gnawux** [comment]
@jgillich It is a dropped access method, the `create` does not use any url parameter. And the `remove` parameter is dropped as well.

**Comment by jgillich** [comment]
Thanks, good to know. Also `/container/create` isn't documented currently.

Anyway, I've decided to just learn Go and use the hyperd client directly, however I'm running in some issues. If I try to compile `0.7.0` with make, I get this:

```
$ make
make[1]: Entering directory '/home/jgillich/devel/src/golinux/vendor/github.com/hyperhq/hyperd'
go build -tags "static_build   libdm_no_deferred_remove exclude_graphdriver_btrfs" -ldflags "-X github.com/hyperhq/hyperd/utils.VERSION=0.7.0" hyperd.go
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x7e1940, 0xc4200101b0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
main.vendoredImportPath(0xc4204d9680, 0xc4202d1c01, 0x1a, 0x3, 0x0)
	/usr/lib/golang/src/cmd/go/pkg.go:463 +0x66c
main.loadImport(0xc4202d1c01, 0x1a, 0xc420498730, 0x4e, 0xc4204d9680, 0xc4204b97e0, 0xc42047d740, 0x1, 0x1, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:333 +0x9ea
main.(*Package).load(0xc4204d9680, 0xc4204b97e0, 0xc420484000, 0x0, 0x0, 0x4)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0xc4202f9321, 0x26, 0xc420211380, 0x74, 0xc4204f5200, 0xc4204b97e0, 0xc4201bc4e0, 0x1, 0x1, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:374 +0x470
main.(*Package).load(0xc4204f5200, 0xc4204b97e0, 0xc420366700, 0x0, 0x0, 0x4)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0xc4203b2be1, 0x1c, 0xc42026f900, 0x4a, 0xc420202480, 0xc4204b97e0, 0xc4202e33e0, 0x1, 0x1, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:374 +0x470
main.(*Package).load(0xc420202480, 0xc4204b97e0, 0xc420115c00, 0x0, 0x0, 0xc)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0xc42048c181, 0x22, 0xc420449310, 0x47, 0xc42041c480, 0xc4204b97e0, 0xc4202a6000, 0x20, 0x20, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:374 +0x470
main.(*Package).load(0xc42041c480, 0xc4204b97e0, 0xc4203faa80, 0x0, 0x0, 0xc)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0xc420254931, 0x1f, 0xc4204114a0, 0x48, 0xc42030f200, 0xc4204b97e0, 0xc420255170, 0x1, 0x1, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:374 +0x470
main.(*Package).load(0xc42030f200, 0xc4204b97e0, 0xc420220000, 0x0, 0x0, 0xc)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.loadImport(0xc4201a1051, 0x20, 0xc420152a00, 0x41, 0xc4201b4000, 0xc4204b97e0, 0xc4201a1590, 0x1, 0x1, 0x1, ...)
	/usr/lib/golang/src/cmd/go/pkg.go:374 +0x470
main.(*Package).load(0xc4201b4000, 0xc4204b97e0, 0xc420189180, 0x0, 0x0, 0xc4201a2860)
	/usr/lib/golang/src/cmd/go/pkg.go:940 +0x12b6
main.goFilesPackage(0xc42000c1b0, 0x1, 0x1, 0x3)
	/usr/lib/golang/src/cmd/go/build.go:830 +0x87e
main.packagesAndErrors(0xc42000c1b0, 0x1, 0x1, 0x487598, 0x20, 0x7f3ac0)
	/usr/lib/golang/src/cmd/go/pkg.go:1687 +0x4f7
main.packagesForBuild(0xc42000c1b0, 0x1, 0x1, 0x893e68, 0xc42001c080, 0x0)
	/usr/lib/golang/src/cmd/go/pkg.go:1719 +0x75
main.runBuild(0xa27420, 0xc42000c1b0, 0x1, 0x1)
	/usr/lib/golang/src/cmd/go/build.go:440 +0xd4
main.main()
	/usr/lib/golang/src/cmd/go/main.go:181 +0x624
Makefile:785: recipe for target 'build-hyperd' failed
make[1]: *** [build-hyperd] Error 2
make[1]: Leaving directory '/home/jgillich/devel/src/golinux/vendor/github.com/hyperhq/hyperd'
Makefile:359: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Any idea what's going on here?

Before that I've simply imported `hyperd/client` via Go, which resulted in all requests being made to `/v/...`, without a version, so all requests 404'd.

**Comment by jgillich** [comment]
Ah I think I know why, I've used glide so hyperd is not below $GOPATH..I guess I have to somehow implement the makefile in my own project. Fun stuff.

**Comment by jgillich** [comment]
Anyway, closing this. If you don't beat my to it, I will create a PR to update this soon-ish.

**Comment by gnawux** [comment]
The undocumented container create API is not fully supported yet, and the implementation will be changed soon.
